### ISSUE TITLE
empty on_screen_label blinking

### ISSUE THREAD

**Issue by co5mo** [romanvm/kodi.yatp#12]
hi roman,
there sometimes appears a rapidly blinking on screen label without any visible text in the top left corner when watching torrent (it is the waiting for piece label)
is there a way to completely disable it to prevent this from happening
using android 4.x fire tv happening also on windows
pic: http://i.imgur.com/J2GaTJH.jpg
errorlog: http://pastebin.com/EExFMC03
thank you so much for yatp and rarbg plugin

**Comment by romanvm** [comment]
Please provide a proper Kodi **debug** log for the issue.

**Comment by co5mo** [comment]
sorry here is the full log from clean kodi portable installation

http://pastebin.com/jwHbErQq

thanks

**Comment by co5mo** [comment]
here it is thanks http://xbmclogs.com/p1eqpgflb

**Comment by romanvm** [comment]
On-screen label during playback is shown when YATP hits a missing piece that has not yet been downloaded. This usually happens when the current download speed is less that the total bitrate of a video + overhead. In this case increasing buffer duration/size and/or pausing a video for some time usually helps.

The label should read "Waiting for piece #XX, DL speed: YYKB/s". But I have no Idea why the text is missing. It is OK on my Windows and Android setups.

**Comment by co5mo** [comment]
there is time when the label shows "Waiting for piece #XX, DL speed: YYKB/s" and it goes away but sometimes it blinks without content, would it be possible to disable this label completely in settings or move it to the bottom? I will try well seeded torrent to test again

**Comment by romanvm** [comment]
I want to provide some feedback to a user when YATP pauses playback on a missing piece. So disabling the label is not an option. But I'll think how it can be re-worked so it won't appear when it is not needed. I'm have some ideas but I'm not sure if they will work because, as I said, I have no idea why the label is blinking. It simply shouldn't.

As for moving the label, it cannot be moved to the bottom because the top-left corner of the screen is the only fixed anchor point on displays with different resolutions. So there is no fixed "bottom". But I can move the label to the top of the screen.

**Comment by romanvm** [comment]
I've reworked the on-screen label and uploaded the update into my addon repo. I this won't help, then I don't know what else can be done.

**Comment by co5mo** [comment]
thank you roman I will test back home!

**Comment by co5mo** [comment]
it is working no more blinking but it looks like some torrents are not meant to be streamed :) 

did you do some advancedsettings.xml changes on the android box?
can you please share your yatp settings.xml?
which port should I forward sever or client?

maybe you should know now the box is now hidden behind the player osd on some skins when paused
thank you again

**Comment by romanvm** [comment]
1. No, I don't use a custom advancedsettings.xml, and all YATP settings are left to their default values, except for a torrent download folder.
2. You need to forward the torrent-client port. But libtorrent supports automatic port-forwarding via UPnP so in most cases you don't need to do anything.
3. Yes, I have moved the on-screen label higher.

**Comment by co5mo** [comment]
thank you
